// <auto-generated />
namespace aid_id.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class no_carbohidratos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(no_carbohidratos));
        
        string IMigrationMetadata.Id
        {
            get { return "201904291123402_no_carbohidratos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
