// <auto-generated />
namespace aid_id.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class analisis_y_comidas_fuuuuuuuuuuuuusion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(analisis_y_comidas_fuuuuuuuuuuuuusion));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251201408_analisis_y_comidas_fuuuuuuuuuuuuusion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
