//------------------------------------------------------------------------------
// <auto-generated>
<<<<<<< HEAD
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
=======
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
>>>>>>> 9beb18f2d79b1691fbc13ad8bd6eba1c16362b63
// </auto-generated>
//------------------------------------------------------------------------------

namespace aid_id.Models.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analisis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analisis()
        {
            this.Comidas = new HashSet<Comidas>();
        }
    
        public long id_analisis { get; set; }
        public byte valor { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<byte> intensidad_deporte { get; set; }
        public long id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comidas> Comidas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
