//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aid_id.Models.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comidas()
        {
            this.Comidas_alimentos = new HashSet<Comidas_alimentos>();
        }
    
        public long id_comida { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string tipocomida { get; set; }
        public Nullable<decimal> carbo_totales { get; set; }
        public Nullable<long> id_analisis { get; set; }
    
        public virtual Analisis Analisis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comidas_alimentos> Comidas_alimentos { get; set; }
    }
}
