//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aid_id.Models.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comidas_alimentos
    {
        public long id_comidas_alimentos { get; set; }
        public Nullable<long> id_comida { get; set; }
        public Nullable<long> id_alimento { get; set; }
    
        public virtual Alimentos Alimentos { get; set; }
        public virtual Comidas Comidas { get; set; }
    }
}
