//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aid_id.Models.BBDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comidas()
        {
            this.Comidas_alimentos = new HashSet<Comidas_alimentos>();
        }
    
        public long id_comida { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string tipocomida { get; set; }
        public Nullable<decimal> carbo_totales { get; set; }
        public Nullable<long> id_analisis { get; set; }
    
        public virtual Analisis Analisis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comidas_alimentos> Comidas_alimentos { get; set; }
    }
}
