use db_diabetes;

-- --------------------------------------------------------------------------
-- 100 INSERT USUARIOS
-- --------------------------------------------------------------------------
/*Nombre, Apellido, Edad, Peso, Altura, Glucideal_min, Glicideal_max, Ratio_ins/gluc, Ratio_ins/Carb*/

INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Raul','Caro','RaulCaro38','123abc','raulcaro38@gmail.com',38,119.41,1.39,80,120,31,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Pol','Carro','PolCarro34','123abc','polcarro34@gmail.com',34,105.47,1.28,80,120,42,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Gerda','Olgin','GerdaOlgin2','123abc','gerdaolgin2@gmail.com',2,63.72,1.36,80,120,44,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Olson','Soriano','OlsonSoriano8','123abc','olsonsoriano8@gmail.com',8,61.62,1.15,80,120,29,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ulises','Jonguitud','UlisesJonguitud13','123abc','ulisesjonguitud13@gmail.com',13,97.75,1.12,80,120,47,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Pablo','Carpintero','PabloCarpintero10','123abc','pablocarpintero10@gmail.com',10,87.56,1.43,80,120,30,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Santiago','Soriano','SantiagoSoriano38','123abc','santiagosoriano38@gmail.com',38,92.54,1.29,80,120,40,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Olson','Haumada','OlsonHaumada15','123abc','olsonhaumada15@gmail.com',15,70.83,1.49,80,120,29,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Freya','Mares','FreyaMares30','123abc','freyamares30@gmail.com',30,50.15,1.31,80,120,28,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Raul','Sotela','RaulSotela30','123abc','raulsotela30@gmail.com',30,94.68,1.34,80,120,46,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mikel','Lisama','MikelLisama5','123abc','mikellisama5@gmail.com',5,73.10,1.16,80,120,36,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Oier','Olachia','OierOlachia6','123abc','oierolachia6@gmail.com',6,68.44,1.02,80,120,48,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Yeray','Barragan','YerayBarragan5','123abc','yeraybarragan5@gmail.com',5,71.10,1.33,80,120,48,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Victor','Marcial','VictorMarcial24','123abc','victormarcial24@gmail.com',24,105.63,1.13,80,120,31,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Siriana','Soliz','SirianaSoliz23','123abc','sirianasoliz23@gmail.com',23,101.23,1.11,80,120,40,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ludmila','Limon','LudmilaLimon0','123abc','ludmilalimon0@gmail.com',0,59.71,1.28,80,120,49,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Santiago','Acencio','SantiagoAcencio24','123abc','santiagoacencio24@gmail.com',24,55.00,1.03,80,120,32,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Krista','Mariano','KristaMariano35','123abc','kristamariano35@gmail.com',35,85.87,1.01,80,120,48,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Narciso','Jauregui','NarcisoJauregui1','123abc','narcisojauregui1@gmail.com',1,76.62,1.02,80,120,32,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mario','Carmel','MarioCarmel5','123abc','mariocarmel5@gmail.com',5,99.26,1.23,80,120,40,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Erik','Acevedo','ErikAcevedo34','123abc','erikacevedo34@gmail.com',34,86.68,1.27,80,120,46,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Marti','Jauri','MartiJauri33','123abc','martijauri33@gmail.com',33,90.58,1.26,80,120,43,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mariano','Carrera','MarianoCarrera9','123abc','marianocarrera9@gmail.com',9,107.60,1.15,80,120,30,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ulises','Olivas','UlisesOlivas9','123abc','ulisesolivas9@gmail.com',9,104.08,1.06,80,120,27,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Victor','Soloriano','VictorSoloriano8','123abc','victorsoloriano8@gmail.com',8,60.28,1.2,80,120,48,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Oriol','Carrion','OriolCarrion9','123abc','oriolcarrion9@gmail.com',9,63.69,1.49,80,120,39,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mikel','Barvosa','MikelBarvosa37','123abc','mikelbarvosa37@gmail.com',37,83.70,1.44,80,120,38,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Siriana','Barroso','SirianaBarroso6','123abc','sirianabarroso6@gmail.com',6,76.63,1.38,80,120,38,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mauricio','Barroso','MauricioBarroso16','123abc','mauriciobarroso16@gmail.com',16,60.81,1.2,80,120,38,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Eyra','Soloriano','EyraSoloriano9','123abc','eyrasoloriano9@gmail.com',9,85.95,1.32,80,120,43,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ivar','Carlon','IvarCarlon2','123abc','ivarcarlon2@gmail.com',2,68.82,1.08,80,120,35,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sergi','Marin','SergiMarin35','123abc','sergimarin35@gmail.com',35,110.31,1.21,80,120,35,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Maximo','Carriyo','MaximoCarriyo33','123abc','maximocarriyo33@gmail.com',33,105.49,1,80,120,40,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Gisli','Soto','GisliSoto36','123abc','gislisoto36@gmail.com',36,57.20,1.18,80,120,30,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Omar','Olgin','OmarOlgin39','123abc','omarolgin39@gmail.com',39,59.41,1.13,80,120,46,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Nilsa','Alaves','NilsaAlaves26','123abc','nilsaalaves26@gmail.com',26,84.30,1.34,80,120,38,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Valkiria','Canelone','ValkiriaCanelone17','123abc','valkiriacanelone17@gmail.com',17,54.48,1.16,80,120,44,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Nathan','Jarquin','NathanJarquin0','123abc','nathanjarquin0@gmail.com',0,59.68,1.03,80,120,32,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ponce','Jaure','PonceJaure36','123abc','poncejaure36@gmail.com',36,94.50,1.25,80,120,26,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sergio','Acero','SergioAcero13','123abc','sergioacero13@gmail.com',13,51.72,1.34,80,120,28,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Placido','Alatorre','PlacidoAlatorre5','123abc','placidoalatorre5@gmail.com',5,93.57,1.25,80,120,26,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ximen','Carion','XimenCarion27','123abc','ximencarion27@gmail.com',27,83.93,1.1,80,120,37,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Yeray','Alatriste','YerayAlatriste14','123abc','yerayalatriste14@gmail.com',14,97.92,1.28,80,120,30,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Samuel','Juares','SamuelJuares40','123abc','samueljuares40@gmail.com',40,111.63,1.42,80,120,32,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Pedro','Suarez','PedroSuarez6','123abc','pedrosuarez6@gmail.com',6,81.34,1.16,80,120,49,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sigrid','Carreto','SigridCarreto38','123abc','sigridcarreto38@gmail.com',38,81.46,1.41,80,120,34,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Pablo','Casanoba','PabloCasanoba5','123abc','pablocasanoba5@gmail.com',5,73.48,1.01,80,120,30,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Matias','Barrientes','MatiasBarrientes18','123abc','matiasbarrientes18@gmail.com',18,51.44,1.21,80,120,35,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sven','Olibera','SvenOlibera13','123abc','svenolibera13@gmail.com',13,105.82,1.18,80,120,49,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Harald','Soto','HaraldSoto3','123abc','haraldsoto3@gmail.com',3,63.88,1.15,80,120,35,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Lena','Baylon','LenaBaylon36','123abc','lenabaylon36@gmail.com',36,113.44,1.41,80,120,46,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Rafael','Olguin','RafaelOlguin39','123abc','rafaelolguin39@gmail.com',39,111.09,1.39,80,120,37,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Raul','Carrizal','RaulCarrizal16','123abc','raulcarrizal16@gmail.com',16,112.11,1.41,80,120,38,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Hans','Casanova','HansCasanova11','123abc','hanscasanova11@gmail.com',11,65.99,1,80,120,38,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Roberto','Casanoba','RobertoCasanoba13','123abc','robertocasanoba13@gmail.com',13,78.77,1.28,80,120,30,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ponce','Carpio','PonceCarpio30','123abc','poncecarpio30@gmail.com',30,59.60,1.14,80,120,32,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Eyra','Albarado','EyraAlbarado41','123abc','eyraalbarado41@gmail.com',41,70.02,1.11,80,120,39,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Rafael','Palomar','RafaelPalomar14','123abc','rafaelpalomar14@gmail.com',14,53.42,1.39,80,120,42,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Vicente','Albares','VicenteAlbares34','123abc','vicentealbares34@gmail.com',34,50.35,1.41,80,120,28,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Kaysa','Alatriste','KaysaAlatriste12','123abc','kaysaalatriste12@gmail.com',12,51.27,1.07,80,120,31,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Miguel','Palma','MiguelPalma34','123abc','miguelpalma34@gmail.com',34,82.09,1.31,80,120,42,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Jorgen','Marroquin','JorgenMarroquin40','123abc','jorgenmarroquin40@gmail.com',40,112.25,1.29,80,120,39,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sebastian','Alatorre','SebastianAlatorre7','123abc','sebastianalatorre7@gmail.com',7,60.14,1.48,80,120,39,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Marcos','Carvajal','MarcosCarvajal1','123abc','marcoscarvajal1@gmail.com',1,67.42,1.11,80,120,38,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ivar','Carriyo','IvarCarriyo35','123abc','ivarcarriyo35@gmail.com',35,53.63,1.26,80,120,39,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Virgilio','Harris','VirgilioHarris27','123abc','virgilioharris27@gmail.com',27,105.71,1.03,80,120,41,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Krista','Barragan','KristaBarragan6','123abc','kristabarragan6@gmail.com',6,65.81,1.04,80,120,49,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Brenda','Cariaga','BrendaCariaga3','123abc','brendacariaga3@gmail.com',3,76.86,1.4,80,120,31,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Harald','Sostenes','HaraldSostenes11','123abc','haraldsostenes11@gmail.com',11,65.19,1.18,80,120,38,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Matias','Palomeque','MatiasPalomeque36','123abc','matiaspalomeque36@gmail.com',36,119.86,1.18,80,120,32,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Pablo','Aceves','PabloAceves18','123abc','pabloaceves18@gmail.com',18,109.61,1.26,80,120,46,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Rogelio','Acha','RogelioAcha5','123abc','rogelioacha5@gmail.com',5,95.68,1.27,80,120,48,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Freya','Baylon','FreyaBaylon2','123abc','freyabaylon2@gmail.com',2,55.86,1.33,80,120,35,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ludmila','Soriano','LudmilaSoriano21','123abc','ludmilasoriano21@gmail.com',21,53.79,1.35,80,120,31,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Virgilio','Soloriano','VirgilioSoloriano40','123abc','virgiliosoloriano40@gmail.com',40,104.99,1.49,80,120,44,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sergi','Olea','SergiOlea9','123abc','sergiolea9@gmail.com',9,70.39,1.37,80,120,43,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Unai','Acevedo','UnaiAcevedo27','123abc','unaiacevedo27@gmail.com',27,73.00,1.11,80,120,40,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ivar','Hernandes','IvarHernandes39','123abc','ivarhernandes39@gmail.com',39,65.23,1.02,80,120,36,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Kaira','Barragan','KairaBarragan22','123abc','kairabarragan22@gmail.com',22,52.31,1.15,80,120,44,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Octavio','Marimon','OctavioMarimon16','123abc','octaviomarimon16@gmail.com',16,61.74,1.34,80,120,37,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Victor','Olaque','VictorOlaque37','123abc','victorolaque37@gmail.com',37,58.57,1.09,80,120,28,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Astrid','Lisarrag','AstridLisarrag24','123abc','astridlisarrag24@gmail.com',24,60.90,1.13,80,120,37,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Ondina','Jaramiyo','OndinaJaramiyo15','123abc','ondinajaramiyo15@gmail.com',15,50.21,1.31,80,120,44,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Helge','Jaramillo','HelgeJaramillo34','123abc','helgejaramillo34@gmail.com',34,58.21,1.18,80,120,41,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Yerai','Aceves','YeraiAceves32','123abc','yeraiaceves32@gmail.com',32,65.33,1.37,80,120,46,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Freya','Carrisal','FreyaCarrisal32','123abc','freyacarrisal32@gmail.com',32,86.47,1.07,80,120,47,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Sergio','Carpintero','SergioCarpintero9','123abc','sergiocarpintero9@gmail.com',9,58.40,1.36,80,120,26,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Urbano','Barros','UrbanoBarros6','123abc','urbanobarros6@gmail.com',6,98.16,1.47,80,120,38,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Samuel','Limon','SamuelLimon27','123abc','samuellimon27@gmail.com',27,57.13,1.02,80,120,33,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Bjorn','Palos','BjornPalos20','123abc','bjornpalos20@gmail.com',20,103.23,1.22,80,120,49,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Jorgen','Carion','JorgenCarion35','123abc','jorgencarion35@gmail.com',35,76.61,1.14,80,120,45,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Maximo','Carrales','MaximoCarrales32','123abc','maximocarrales32@gmail.com',32,102.65,1.41,80,120,47,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Egil','Olibares','EgilOlibares10','123abc','egilolibares10@gmail.com',10,99.98,1.18,80,120,34,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Helga','Mariano','HelgaMariano29','123abc','helgamariano29@gmail.com',29,96.34,1.04,80,120,27,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Daven','Haumada','DavenHaumada11','123abc','davenhaumada11@gmail.com',11,117.58,1.08,80,120,28,9,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Octavio','Carrisal','OctavioCarrisal21','123abc','octaviocarrisal21@gmail.com',21,92.06,1.23,80,120,37,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Mohamed','Soto','MohamedSoto17','123abc','mohamedsoto17@gmail.com',17,55.90,1.25,80,120,33,10,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Harald','Bazan','HaraldBazan37','123abc','haraldbazan37@gmail.com',37,54.68,1.04,80,120,45,11,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Niels','Soriano','NielsSoriano3','123abc','nielssoriano3@gmail.com',3,92.49,1.16,80,120,35,8,20);
INSERT INTO USUARIOS (nombre, apellido, usuario, passcode, correo, edad, peso, altura, glucemia_min, glucemia_max, r_insulina_gluc, r_insulina_carb, total_insulina_diaria) VALUES ('Viggora','Palmerin','ViggoraPalmerin37','123abc','viggorapalmerin37@gmail.com',37,112.32,1.11,80,120,42,9,20);
SELECT * FROM USUARIOS;
-- --------------------------------------------------------------------------
-- 10 INSERT ANALISIS
-- --------------------------------------------------------------------------
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 50, 1);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (135, GETDATE(), 60, 1);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (115, GETDATE(), 25, 1);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 50, 1);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (140, GETDATE(), 0, 2);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (150, GETDATE(), 80, 2);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (130, GETDATE(), 60, 2);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 50, 2);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 5, 3);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 75, 3);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 33, 3);
INSERT INTO ANALISIS (valor, fecha_hora, intensidad_deporte, id_usuario) VALUES (120, GETDATE(), 80, 3);

SELECT * FROM ANALISIS;
-- --------------------------------------------------------------------------
-- 10 INSERT ALIMENTOS
-- --------------------------------------------------------------------------
USE db_diabetes;
INSERT INTO ALIMENTOS(nombre, carbohidratos, proteinas, grasas) VALUES ('Acedias Fritas', 12.0, 17.0, 16.0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite de Cacahuete', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite de Coco', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite Girasol', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite Maíz', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite Oliva', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite Soja', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceite Uva, Pepita', 0, 0, 100);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aceitunas Salmuera', 0, 1, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Acelgas', 1, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Acerolas', 8, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Agua Manantial', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Aguacate', 2, 4, 22);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ajo', 28, 6, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Albaricoque', 7, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Alcachofas', 3, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Almeja / Chirla', 0, 11, 0.9 );
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Almendras', 4, 17, 54);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ancas Rana, De', 0, 16, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Anchoas Enlatadas', 0, 22, 13);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Anguila', 0, 17, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Angulas', 0, 16, 16);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Anisete', 2, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Apio', 1, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Arenque Ahumado', 0, 26, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Arenque Seco', 0, 17, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Arroz Integral', 77, 7, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Arroz Leche, Con', 13, 3, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Arroz Pulido, Blanco', 87, 6, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Atún Conserva', 0, 23, 22);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Atún Fresco', 0, 22, 16);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Avellanas', 7, 8, 36);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Avena, Salvado', 2, 2, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Azúcar Blanca', 100, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Azúcar Morena', 96, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bacalao Fresco', 0, 17, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bacalao Salazón, remojado', 0, 32, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bacalao Seco', 0, 75, 2.5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bacón', 0, 14, 41);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Banana', 11, 3, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Batata', 22, 1, 1 );
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Batido Chocolate', 77, 6, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Berberechos Cocidos', 0, 11, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Berenjenas', 3, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Berros', 1, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bígaros Cocidos', 5, 26, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Biscotes Trigo', 73, 9, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Besugo', 0, 16, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bollos-Pastas Media', 49, 5, 20);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Bombones Media', 66, 5, 21);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Breca', 1, 15, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Brécol', 2, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Brócoli', 2, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Butifarra', 0, 15, 20);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Caballa', 0, 19, 16);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Caballo Carne', 0, 21, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cabra Carne', 0, 20, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cabrito Carne', 0, 20, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cacahuetes Tostados', 9, 24, 49);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cacao Polvo', 11, 20, 24);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Café Extracto, Polvo', 8, 11, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Café Infusión', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Café Instantáneo', 11, 15, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Café Torrefacto', 2, 13, 13);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Calabacín', 4, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Calabaza', 3, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Calamar-Sepia', 0.5, 17, 1.3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cangrejo', 0, 20, 1.6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Caqui', 15, 0.5, 0.1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Caracol Terrestre', 0, 16, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cardo', 4, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Caballo', 0, 21, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cabra', 0, 20, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cabrito', 0, 20, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cerdo, Grasa', 0, 16, 30);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cerdo, Magra', 0, 21, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Conejo', 0, 22, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cordero, Chuleta', 0, 15, 36);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cordero, Magra', 0, 20, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cordero, Paletilla', 0, 16, 28);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Cordero, Pierna', 0, 18, 19);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Oveja', 0, 18, 17);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Ternera, Magra', 0, 21, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Vaca, Chuleta', 0, 16, 25);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Vaca, Filete', 0, 19, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Vaca, Guisar', 0, 20, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Vaca, Magra', 0, 20, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Carne Vaca, Solomillo', 0, 17, 23);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Castañas', 37, 2, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Caviar Ruso', 0, 26, 16);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cebada', 84, 8, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cebolla', 5, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Centollo', 0, 20, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cereales Cornflakes', 85, 9, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cereales Muesli', 66, 13, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cereales Weetabix', 70, 11, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cerezas', 12, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cerveza Lager', 2, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cerveza Negra', 3, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Champán', 3, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Champiñón', 0, 2, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chanquetes', 2, 11, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cheese, Burger. McDonald', 30, 15, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cheetos Queso, Golosina', 15, 2, 10);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chicharro', 1, 16, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chicharrones', 1, 20, 51);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chicle', 95, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chirimoya', 0, 19, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chocolate con leche', 56, 6, 34);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Chocolate sin leche', 63, 2, 30);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cigala', 0, 15, 0.8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Coco', 16, 6, 62);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Col', 4, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Coles Bruselas', 3, 4, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Coliflor', 2, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Conejo', 0, 22, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Congrio', 0, 20, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Conguitos', 13, 5, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Coñac', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Corazón Cordero', 0, 17, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Corazón Vacuno', 0, 19, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cordero Carne, Magra', 0, 20, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cordero Paletilla', 0, 16, 28);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cordero Pierna', 0, 18, 19);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cornflakes', 85, 9, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Crema Champán, De', 5, 1, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Crema chocolate con avellanas', 60.5, 6.2, 33);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Crema Leche, Chantilly', 10, 2, 31);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cuajada', 6, 5, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Cubitos Sopa', 8, 23, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Dátiles', 71, 2.2, 0.4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Dátiles Secos Deshuesados', 64, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Diet-Coke', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Dorada', 0, 20.82, 6.34);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Emperador', 0, 19, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Endibias', 1, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Espárragos Cocidos', 1, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Espárragos Enlatados', 1, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Espinacas', 1, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Espinacas Cocidas', 1, 5, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Extracto Carne', 3, 38, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Faisán', 0, 24, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Faneca', 1, 15, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Filete Vaca', 0, 19, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Flan Huevo, De', 22, 5, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Foie-Gras', 0, 14, 46);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Frambuesas', 6, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Fresas', 6, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Galletas Mantequilla', 75, 8, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Galletas Media', 74, 7, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Galletas Saladas', 76, 9, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Gallo', 0, 17, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Gambas Cocidas', 0, 23, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Garbanzos', 49, 20, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Gatorade', 10, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Germen Trigo', 24, 27, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ginebra', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Gofio Millo', 83, 6, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Gofio Trigo', 82, 11, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Granada', 17, 1, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Grelos', 0, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Guisantes Enlatados', 9, 4, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Guisantes Frescos', 11, 6, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Habas secas', 59, 23, 1.5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hamburguesa Burger- King', 29, 15, 13);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hamburguesas Vacuno', 5, 15, 20);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Avena', 73, 12, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Centeno', 68, 7, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Maíz', 92, 0, 1 );
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Soja', 24, 37, 24);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Trigo, Integral', 66, 13, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Harina Trigo, Panificada', 75, 11, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Helado', 21, 4, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Helado Fruta', 29, 2, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hígado Cerdo', 2, 21, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hígado Cerdo', 2, 21, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hígado Pollo', 1, 19, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Hígado Ternera', 2, 20, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Higos Secos', 53, 4, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Higos Verdes', 10, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Huevo', 1, 12, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Huevo Duro', 1, 12, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Huevo Yema, Liquida', 0, 16, 32);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Jamón Cocido', 1, 22, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Judías secas', 60, 19, 1.5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Jurel', 1, 16, 7);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ketchup', 24, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Kiwi', 11, 1, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Langosta Cocida', 0, 22, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Langostino', 0, 21, 1.4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche de Cabra', 5, 3, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche de Mujer', 7, 1, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Desnatada, Polvo', 53, 35, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Entera, Polvo', 37, 25, 26);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Vaca, Entera', 5, 3, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Vaca, Estéril', 5, 3, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Vaca, Semidesnatada', 5, 3, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche Vaca, U.H.T.', 5, 3, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche, Condensada Azucarada', 52, 8, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Leche, Condensada M.G., 7,50 %', 10, 6, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Lechuga', 1, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Lenguado', 0, 17, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Lentejas', 53, 24, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Levadura Cerveza, Seca', 0, 48, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Limón', 3, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Limonada Envasada', 6, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Lombarda', 4, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Lomo, Cerdo Embuchado', 0, 50, 21);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Macarrones', 79, 14, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Magdalena', 42, 6, 23);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Maíz, Dulce Mazorca', 23, 4, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mandarinas', 8, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mango', 12.45, 0.6, 0.47);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Manhattan Cocktail', 8, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Manteca Cerdo', 0, 0, 99);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mantequilla', 0, 0, 82);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Manzana', 12, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Margarina Industrial', 0, 0, 80);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Margarina Vegetal', 0, 0, 80);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Martini', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mayonesa', 0, 2, 79);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mazapán', 49, 9, 25);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Mejillones', 0, 12, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Melocotón', 9, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Melocotón en almíbar', 22, 0.4, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Melón', 5, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Membrillo', 59, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Merluza', 11, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Miel', 75, 0.5, 0.2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Naranja', 6, 2, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Nectarina', 17.1, 0.6, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Nueces', 5, 11, 52);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Nuez Brasil', 4, 12, 62);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ostras', 5, 9, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Palmitos Enlatados', 8, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Paloma', 0, 22, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Palomitas Maíz', 11, 2, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Palosanto', 15, 0.5, 0.1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pan Blanco', 50, 8, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pan Con Chocolate', 51, 7, 21);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pan Integral', 42, 9, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pan Tostado, Blanco', 65, 10, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Papaya', 10.3, 0.6, 0.2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pasta', 82, 13, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Patata cocida', 19, 2, 0.1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Patatas Fritas', 37, 4, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pato', 0, 16, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pavo', 0, 22, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pepino', 2, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pepinillos en vinagre', 2.1, 0.7, 0.1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Peras', 11, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Percebes', 0, 14, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Perdiz', 0, 23, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Perejil', 0, 5, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Perrito-Caliente Con Mostaza', 33, 11, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pescadilla', 0, 21, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Petit-Suisse Queso, Tipo', 4, 8, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pichón', 0, 21, 10);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pimiento', 2, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Piña', 12, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Piña Almíbar, En', 20, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Piñones', 15, 15, 60.4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pipas Girasol', 14, 22, 50);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pistachos', 13, 21, 52);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pizza Queso, Tomate', 25, 9, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Plátano', 19, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pollo', 0, 20, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pollo, Frito Kentucky', 5, 13, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pollo, Pechugas Kentucky', 34, 25, 22);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pomelo', 5, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Puerro', 6, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Pulpo', 2, 11, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Azul', 0, 23, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Babibel, Tipo', 0, 23, 25);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Brie', 1, 23, 28);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Burgos', 3, 11, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Cabra', 2, 17, 18);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Camembert', 0, 23, 23);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Chédar', 0, 26, 34);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Emmental', 0, 29, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Gouda', 0, 25, 27);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Gruyere', 0, 26, 34);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Mozzarella', 0, 20, 16);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Parmesano', 0, 35, 30);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Pirineos', 0, 22, 30);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Porciones', 1, 18, 23);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Quark', 3, 11, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso Roquefort', 0, 23, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso, Blanco Desnatado', 3, 10, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso, Fresco Mg., 20 %', 4, 8, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso, Manchego Curado', 1, 32, 32);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso, Manchego Fresco', 0, 26, 25);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Queso, Manchego Semicurado', 0, 29, 29);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Quiche Lorraine Bacón-Queso', 21, 15, 28);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Rábano', 3, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Rabo Vacuno', 0, 20, 10);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Rape', 0, 17, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Raviolis Tomate, Salsa', 13, 5, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Refresco Ligth', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Remolacha Cocida', 10, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Rodaballo', 1, 16, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Ron', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sal', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salami', 2, 19, 45);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salchichas Cerdo', 10, 11, 32);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salchichas Enlatadas', 0, 13, 20);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salchichas Fráncfort', 3, 10, 25);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salchichón', 2, 26, 38);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salmón', 0, 18, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salmón ahumado', 0, 20, 8.2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salmonete', 2, 14, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salsa Boloñesa', 2, 8, 11);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salsa Ketchup', 24, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salsa Queso', 9, 8, 15);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Salvado Trigo', 27, 14, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sandia', 8, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sangre Vacuno', 0, 18, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sardinas', 0, 19, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sardinas Con Tomate, Lata', 0, 18, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sardinas En Aceite', 0, 24, 14);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sepia', 0, 16, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sésamo', 10, 19, 50);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sesos Cerdo', 0, 11, 9);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sesos Cordero', 0, 10, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sesos Ternera', 0, 10, 8);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Setas Boletus, Edulis', 0, 3, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Setas Cantharellus', 0, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Setas Colmenilla', 0, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Seven-Up', 36, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sidra', 3, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Soja Brotes', 1, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Soja Germinada', 1, 2, 0.1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sopa De Cebolla', 2, 2, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Sopa Minestrone', 5, 2, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Speisequark Tipo Queso', 3, 10, 5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tapioca', 95, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tarta Manzana Casera', 43, 2, 12);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Te Infusión', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tocino', 0, 14, 41);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tomate', 3, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tomate Frito', 3, 1, 6);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tomate triturado', 5.5, 2.3, 0.5);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Tónica Agua', 10, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Trucha', 0, 16, 3);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Trufas', 0, 6, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Turrón Media', 57, 10, 24);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Uvas', 16, 1, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Uvas Pasas', 63, 2, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vermut Seco', 6, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vieiras', 0, 16, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vinagre De Vino', 1, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vino Blanco', 3, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vino Oporto', 12, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vino Rosado', 2, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Vinotinto', 0, 0, 0);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yema Huevo Liquida', 0, 16, 32);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Con Nata', 4, 4, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Desnatado', 6, 5, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Frutas', 19, 4, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Liquido', 11, 3, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Natural', 6, 5, 4);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur Sabores', 14, 4, 2);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogur, Frutas Semidesnatado', 18, 5, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Yogurt Desnatado', 6, 5, 1);
INSERT INTO ALIMENTOS (nombre, carbohidratos, proteinas, grasas) VALUES ('Zanahoria', 9, 1.2, 0.3);

SELECT * FROM ALIMENTOS;
-- --------------------------------------------------------------------------
-- 10 INSERT COMIDAS
-- --------------------------------------------------------------------------
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'DESAYUNO', 500, 1);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'ALMUERZO', 500, 2);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'COMIDA', 500, 3);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'MERIENDA', 500, 4);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'CENA', 500, 5);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'VERMUT', 500, 6);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'PISCOLABI', 500, 7);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'OTROS', 500, 8);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'DESAYUNO', 500, 9);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'ALMUERZO', 500, 10);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'COMIDA', 500, NULL);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'MERIENDA', 500, NULL);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'CENA', 500, NULL);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'VERMUT', 500, NULL);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'PISCOLABI', 500, NULL);
INSERT INTO COMIDAS (fecha_hora, tipocomida, carbo_totales, id_analisis) VALUES (SYSDATETIME(), 'OTROS', 500, NULL);

SELECT * FROM COMIDAS;
-- --------------------------------------------------------------------------
-- 10 INSERT COMIDAS_ALIMENTOS
-- --------------------------------------------------------------------------
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (1, 1);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (1, 2);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (1, 3);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (2, 2);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (2, 3);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (2, 4);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (3, 1);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (3, 5);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (4, 8);
INSERT INTO COMIDAS_ALIMENTOS (id_comida, id_alimento) VALUES (4, 6);


SELECT * FROM COMIDAS_ALIMENTOS;
