//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alimentos()
        {
            this.Comidas_alimentos = new HashSet<Comidas_alimentos>();
        }
    
        public long id_alimento { get; set; }
        public string nombre { get; set; }
        public decimal carbohidratos { get; set; }
        public decimal proteinas { get; set; }
        public decimal grasas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comidas_alimentos> Comidas_alimentos { get; set; }
    }
}
