//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analisis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analisis()
        {
            this.Comidas = new HashSet<Comidas>();
        }
    
        public long id_analisis { get; set; }
        public byte valor { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public Nullable<byte> intensidad_deporte { get; set; }
        public long id_usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comidas> Comidas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
