//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.Analisis = new HashSet<Analisis>();
        }
    
        public long id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string usuario { get; set; }
        public string passcode { get; set; }
        public string correo { get; set; }
        public byte edad { get; set; }
        public byte peso { get; set; }
        public decimal altura { get; set; }
        public byte glucemia_min { get; set; }
        public byte glucemia_max { get; set; }
        public byte r_insulina_carb { get; set; }
        public byte r_insulina_gluc { get; set; }
        public short total_insulina_diaria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Analisis> Analisis { get; set; }
    }
}
